name: Build

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Install specific rust version
        run: |
          rustup install ${{ matrix.rust }} --profile minimal
          rustup component add --toolchain ${{ matrix.rust }} rustfmt clippy
      - name: Compile
        run: cargo +${{ matrix.rust }} build
      - name: Test example
        working-directory: example
        run: cargo +${{ matrix.rust }} run --locked --verbose -- --ignored
      - name: Run Tests
        env:
          TEST_SWIFT_RS: "true"
        run: cargo +${{ matrix.rust }} test --features build --locked --verbose
      - name: Check Code Formatting
        if: ${{ matrix.rust == 'stable' || matrix.rust == 'beta' }}
        run: cargo +${{ matrix.rust }} fmt --all -- --check
      - name: Lints
        if: ${{ matrix.rust == 'stable' || matrix.rust == 'beta' }}
        run: cargo +${{ matrix.rust }} clippy --all-targets -- -D warnings
